check trailing whitespaces in changed files

diff --git a/.github/workflows/Multixscale:_trailing_whitespace.yml b/.github/workflows/Multixscale:_trailing_whitespace.yml
--- a/.github/workflows/Multixscale:_trailing_whitespace.yml
+++ b/.github/workflows/Multixscale:_trailing_whitespace.yml
@@ -21,8 +21,28 @@ jobs:
               - 'src/OBMD/**'
               - 'examples/OBMD/**'
       - if: steps.changes.outputs.src == 'true'
-        run: echo ${{ steps.changes.outputs.changed_files }}
+        run: |
+          set -e
 
-  
-    
-  
+          tw_lines=""
+
+          for file in (${{ steps.changes.outputs.changed_files }})
+          do
+            lines=$(egrep -rnIH " +$" $file | cut -f-2 -d ":")
+            if [ ! -z "$lines" ]; then
+              tw_lines+=$([[ -z "$tw_lines" ]] && echo "$lines" || echo $'\n'"$lines")
+            fi
+          done
+
+          exit_code=0
+
+          # If tw_lines is not empty, change the exit code to 1 to fail the CI.
+          if [ ! -z "$tw_lines" ]; then
+            echo -e "\n***** Lines containing trailing whitespace *****\n"
+            echo -e "${tw_lines[@]}"
+            echo -e "\nFailed.\n"
+            exit_code=1
+          fi
+
+          exit $exit_code
+ 
